handling all files first
django-repo/django-throttle pull request #1
Opened 2019-05-09 21:52 UTC by sodrooome

2019-05-11 20:02 UTC, andigortz requested changes

2019-05-11 20:02 UTC, andigortz commented on src/throttle/exceptions.py
> +class ThrottlePreventFunctionNotDefined(ImproperlyConfigured):
this is actually so wrong, for a while we don't use `PreventFunction` since the function itself is related with user

2019-05-12 11:04 UTC, sodrooome commented
alright just keep it for later

2019-05-12 11:08 UTC, andigortz approved these changes

2019-05-12 11:10 UTC, merged